
site_name: Cybersecurity Engineering
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
    - scheme: slate
      primary: indigo
      accent: deep purple
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.suggest
  extra_css:
    - assets/branding/extra.css
plugins:
  - search
  - awesome-pages
nav:
  - Home: cybersecurity-engineering-course/docs/index.md
  - Foundations:
      - Intro: /cybersecurity-engineering-course/section-01-foundations/README.md
      - Lab 1: /cybersecurity-engineering-course/section-01-foundations/lab/lab1-basic-linux.md
  - Security Environment:
      - Lab 2: sec-env/labs/lab2.md
  - Web Security:
      - Lab 3: web-sec/labs/lab3.md
  - Linux Hardening:
      - Lab 4: hardening/labs/lab4.md
  - Cloud Security:
      - Lab 5: cloud/labs/lab5.md
  - SIEM & Logging:
      - Lab 6: siem/labs/lab6.md
  - Detection Engineering:
      - Rules: detection/rules.md
  - DevSecOps:
      - Lab 7: devsecops/labs/lab7.md
  - Capstone: 
      - capstone
