
site_name: Security Engineering
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
    - scheme: slate
      primary: indigo
      accent: deep purple
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.suggest
  extra_css:
    - assets/branding/extra.css
plugins:
  - search
  - awesome-pages
nav:
  - Home: README.md
  - Foundations:
      - Intro: docs/foundations/readme.md
      - Lab 1: docs/foundations/labs/lab1.md
  - Build Your Home Lab:
      - Intro: docs/sec-env/readme.md
      - Lab 1: docs/sec-env/labs/lab1.md
      - Lab 2: docs/sec-env/labs/lab2.md
      - Lab 3: docs/sec-env/labs/lab3.md
      - Lab 4: docs/sec-env/labs/lab4.md
  - Web Security:
      - Lab 3: web-sec/labs/lab3.md
  - Linux Hardening:
      - Lab 4: hardening/labs/lab4.md
  - Cloud Security:
      - Lab 5: cloud/labs/lab5.md
  - SIEM & Logging:
      - Lab 6: siem/labs/lab6.md
  - Detection Engineering:
      - Rules: detection/rules.md
  - DevSecOps:
      - Lab 7: devsecops/labs/lab7.md
  - Capstone: 
      - capstone: docs/capstone/readme.md
